---
name: module3_task3

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run on'
        required: false

jobs:
  validate:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set bash shell
        run: echo "SHELL=/bin/bash" >> $GITHUB_ENV

      - name: Install Hugo
        run: sudo apt-get install hugo

      - name: Setup Hugo
        run: |
          cd module3_task2/
          sudo ./setup.sh

      - name: lint
        run: |
          cd ./module3_task2/
          make lint

      - name: Validate Makefile
        run: cd ./module3_task2/ && make help

      - name: build
        run: |
          cd ./module3_task2/
          make build
          make package

      - name: help
        run: |
          make -C ${{ github.workspace }}/module3_task2/ help

      - name: post
        run: |
          cd ./module3_task2/
          make post POST_NAME=who-are-we POST_TITLE="Who are we" post

      - name: Integration test
        run: |
          cd ./module3_task2/
          make unit-tests
          make integration-tests
          make package
          make validate
          make clean

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: ./module3_task3/awesome-website.zip

      - name: clean
        run: |
          cd ./module3_task3/
          make clean
