name: Module 3 Task 1 Workflow

on:
    push:
      branches:
        - main
    schedule:
      - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment and install required tools
        run: |
          chmod +x setup.sh
          ./setup.sh

      - name: Build the project
        run: make build

      - name: Create new post
        run: make post

      - name: Clean dist folder
        run: make clean

      - name: Display available targets and descriptions
        run: make help

