name: module3_task1

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set bash shell
        run: echo "SHELL=/bin/bash" >> $GITHUB_ENV

      - name: Validate Makefile
        run: cd ./module3_task1/ && make help

      - name: build
        run: |
          pwd && ls

      - name: help
        run: |
          make -C ${{ github.workspace }}/module3_task1/ help

      - name: post
        run: |
          make post POST_NAME=who-are-we POST_TITLE="Who are we" post
        working-directory: ./module3_task1/

      - name: clean
        run: |
          make clean
          ls
