name: module3_task1

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate Makefile
        run: cd ./module3_task1/ && make help

      - name: Build and Validate
        run: |
          pwd
          ls
          sudo ./module3_task0/setup.sh
          make help
          make build
          make POST_NAME=who-are-we POST_TITLE="Who are we" post
          make clean
          ls
